image: "instrumentisto/rust:nightly"

.default:
  interruptible: true

# Use cargo to test the project
run-tests:
  stage: test
  script:
    - rustc --version && cargo --version && cargo +nightly --version  # Print version info for debugging
    - cargo +nightly test --workspace --verbose --all-features

# For this job, the Settings -> Merge requests -> "Enable merged results pipelines" option should be enabled.
# This ensures that the main branch will always have working tests and no formatting/Clippy issues
merge-request:
  stage: test
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo +nightly test --workspace --verbose --all-features
    - cargo fmt --all --check
    - cargo +nightly clippy --workspace --all-features --examples --tests -- -D warnings
  rules:
    # Only run this job for merge requests which are **not** in the draft state
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TITLE !~ /^Draft.*$/
