image: "instrumentisto/rust:beta"

.default:
  interruptible: true

# Use cargo to test the project
run-tests:
  stage: test
  script:
    - rustc --version && cargo --version  # Print version info for debugging
    - cargo test --workspace --verbose --all-features

# For this job, the Settings -> General -> Merge requests -> Enable merged results pipelines option should be enabled.
# This ensures that the main branch will always have working tests and no formatting/clippy issues
merge-request:
  stage: test
  before_script:
    - rustup component add rustfmt
    - rustup component add clippy
  script:
    - cargo test --workspace --verbose --all-features
    - cargo fmt --all --check
    - cargo clippy --all --all-features
  rules:
    # Only run this job for merge requests which are **not** in the draft state
    - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_COMMIT_TITLE =~ /Merge branch.*/
