[package]
name = "gmw-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitvec = { version = "1.0.0", features = ["serde"]}
tokio = { version = "1.17.0", features = ["full"]}
futures = "0.3.21"
thiserror = "1.0.30"
pin-project = "1.0.10"
nom = "7.1.0"
petgraph = "0.6.0"
smallvec = { version = "1.8.0", features = ["union", "const_generics", "serde"]}
itertools = "0.10.3"
tokio-serde = { version = "0.8.0", features = ["bincode"]}
tokio-util = { version = "0.7.0", features = ["codec"]}
serde = { version = "1.0.136", features = ["derive"]}
tracing = "0.1.32"
itoa = "1.0.1"

[dev-dependencies]
aes = "0.8.1"
anyhow = "1.0.56"
hex-literal = "0.3.4"
tracing-subscriber = { version = "0.3.9", features = ["env-filter"]}