name: CI

on: ["push", "pull_request"]

env:
  CARGO_TERM_COLOR: always

jobs:
  Test:
    runs-on: "ubuntu-latest"
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run tests
        run: cargo test --workspace --verbose --all-features --no-fail-fast